### PR TITLE
Profile image no collapse

### PR DESCRIPTION
**Pull request by utsavm9**
Profile photo now does not collapse and edit button is now edit icon.

### CODE REVIEW

**Comment by malsf21** [comment]
Alternatively, just leave the edit button as the word for now, and we can revisit this later - it's semi-important that we get this change through somewhat early.

**Comment by utsavm9** [comment]
Merging this branch with the font-awesome branch...

**Comment by utsavm9** [comment]
All changes of this branch are now in font-awesome branch. Merge that when complete to stable/master.

**Comment by malsf21** [comment]
Hey Utsav,

You should avoid merging different feature branches into the same PR in the future - but since you've already made the changes, I'll allow it this time.

**Comment by utsavm9** [comment]
Sorry! I though this was the quickest way to bring font awesome edit icon into this.

**Comment by malsf21** [comment]
Yeah, I understand that, and it's a bit tricky. In the future, you can remerge master back into this branch, use git cherry pick, or use a few other workarounds to make it all work out.

**Pull request closed without merging**
