### PR TITLE
issue#744 Hide forgot password while login in

### LINKED ISSUE #744: bug: on login, loading spinner overlaps with "forgot password" section
Relatively self-explanatory; see this screencast:

https://user-images.githubusercontent.com/14893287/142161295-fc73d0c3-14aa-4ad8-b534-51c6862a9e09.mov

### PR DESCRIPTION
**Pull request by LucasGabrielBecker**
For me it makes more sense to hide the `forgot password` option, since the user already hit enter and its waiting to login
Let me know if you guys disagree.
Closes #744

### CODE REVIEW

**Review by lumisphere902 — APPROVED** [review]
LGTM. There are some lint errors, but I am fine with ignoring them due to a refactor currently happening.

**Review by mattxwang — CHANGES_REQUESTED** [review]
> LGTM. There are some lint errors, but I am fine with ignoring them due to a refactor currently happening.

I think we should resolve the lint error and then rebase (whichever thing gets merged first), since ideally we never break `master`/`main`. Ultimately your call though!

Functionality looks good to me though!

**Comment by lumisphere902** [comment]
#751 was merged, so after resolving those conflicts, the lint errors should be gone and you should be good to merge! :)

**Review by mattxwang — APPROVED** [review]
LGTM! Thanks for your contribution Lucas!

**Comment by lumisphere902** [comment]
@LucasGabrielBecker you'll need to merge in new changes from master, and then you should be good to squash and merge :)

**Comment by LucasGabrielBecker** [comment]
I'm not able to merge it, can someone do it ?

**Pull request merged**
