### PR TITLE
bump reactstrap from 8.10.1 to 9.0.1 

### LINKED ISSUE #682: Bump Reactstrap/Bootstrap version
https://getbootstrap.com/docs/5.0/migration/

The main breaking change that applies to us is the removal of `InputGroupAddon`

### PR DESCRIPTION
**Pull request by jaczhi**
Resolves #682 

bump reactstrap from 8.10.1 to 9.0.1 

also fix breaking changes to ShareSketchModal.js due to removal of InputGroupAddon

p.s. minor side note but apologies about the 7 commits, i'm not sure why the failed pre-commits are registering as commits now, i'll have to look into that

### CODE REVIEW

**Comment by jaczhi** [comment]
Hmm, it seems like this new version of ReactStrap adds a few more attributes into the components it produces, breaking the snapshot test. I'll probably look into it more to make 100% sure I didn't break DropdownButton before updating the snapshots.

**Comment by lumisphere902** [comment]
Ok, what are the additional attributes are?

**Comment by jaczhi** [comment]
The `addonType={false}` attribute is removed in all snapshots and the `modifiers={Array []}` attribute is added. The first one makes sense and I don't think the second one affects functionality whatsoever for our usage.

**Review by lumisphere902 — APPROVED** [review]
LGTM to just update the snapshots and merge

**Pull request merged**
