### PR TITLE
Bump standard Node version to 14 LTS.

### PR DESCRIPTION
**Pull request by krashanoff**
Real small PR. Updates our Node version to 14 LTS standard. This is reflected in our `.nvmrc`, GitHub Actions, and README. I don't think I missed anything.

### CODE REVIEW

**Comment by krashanoff** [comment]
Output from Netlify:

```
8:56:05 PM: $ npm run staging_build
8:56:05 PM: > teachla-frontend@0.1.0 staging_build /opt/build/repo
8:56:05 PM: > cross-env REACT_APP_FS_PROJ=staging REACT_APP_SERVER_TYPE=staging react-scripts build
8:56:08 PM: Creating an optimized production build...
8:56:57 PM: Failed to compile.
8:56:57 PM: 
8:56:57 PM: ./src/styles/global.scss
8:56:57 PM: Missing binding /opt/build/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node
8:56:57 PM: Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 14.x
8:56:57 PM: Found bindings for the following environments:
8:56:57 PM:   - Linux 64-bit with Node.js 12.x
8:56:57 PM: This usually happens because your environment has changed since running `npm install`.
8:56:57 PM: Run `npm rebuild node-sass` to download the binding for your current environment.
8:56:58 PM: npm ERR! code ELIFECYCLE
8:56:58 PM: npm ERR! errno 1
8:56:58 PM: npm ERR! teachla-frontend@0.1.0 staging_build: `cross-env REACT_APP_FS_PROJ=staging REACT_APP_SERVER_TYPE=staging react-scripts build`
8:56:58 PM: npm ERR! Exit status 1
8:56:58 PM: npm ERR!
8:56:58 PM: npm ERR! Failed at the teachla-frontend@0.1.0 staging_build script.
8:56:58 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
8:56:58 PM: npm ERR! A complete log of this run can be found in:
8:56:58 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-02-23T04_56_58_184Z-debug.log
```

Probably just need to do as it says and fix our SASS bindings. This is the same problem as in #379.

**Comment by mattxwang** [comment]
@krashanoff do you want to try retriggering the build but clearing the cache? AFAIK there are problems with `npm ci` and caching `node_modules` in between node version upgrades.

**Comment by mattxwang** [comment]
Not sure if we ended up not following up on this PR, but I manually triggered the Netlify redeploy and it worked.

@lumisphere902 you're good to review and merge; since `npm install` breaks between node versions, you may just need to retrigger the netlify deploy after you merge this PR. Lmk if you need more!

**Review by mattxwang — APPROVED** [review]
For posterity, LGTM!

**Pull request merged**
