### PR TITLE
Refactoring App Container Structure (Editor -> TextEditor, Output)

### PR DESCRIPTION
**Pull request by jamieliu386**
Refactored the Editor component (now Main) into separate TextEditor and Output components.

### CODE REVIEW

**Comment by malsf21** [comment]
Since this is a huge PR, going to make a few of us review this before we merge. Regardless, solid work so far Jamie!

**Comment by malsf21** [comment]
Noted bugs so far:

- [ ] radio collapse not working going from large -> small viewport
- [ ] download code button doesn't work
- [ ] error in height value for editor props?

**Comment by malsf21** [comment]
@fan-matt are you sure you've got the latest changes? On my end (just pulled and ran locally) things look just fine. 

Screen Shot 2019-11-25 at 5 12 05 PM

**Comment by fan-matt** [comment]
Must be an issue with netlify. Cloned locally, looks good. Sorry

**Pull request merged**
