### PR TITLE
New Login Page Design & Unifying Login/CreateUser

### PR DESCRIPTION
**Pull request by malsf21**
@emmyc killing the game 💯 (more docs coming soon)

to-do:
- [x] BUG: does not work on screens that are too tall/large
- [x] more above-the-fold content: re-add Teach LA logo, link to GH repo, link to main site
- [x] change accent color of button & inputs to page theme color
- [x] adjust create user to use similar style
- [x] ~add a bit more information to create user~
- [x] better alt tags for image
- [x] fix "forgot your password" component - maybe this is a modal or another page?
- [x] new color button (optional but I think it'd be cool)

also, should we consider randomizing the SVG? just a thought 😮 

and... tests?

and eventually, we should have a static feature page. probably out of scope for this PR!

### CODE REVIEW

**Comment by krashanoff** [comment]
Emmy the MVP 💯 

All the changes are b e a u t i f u l as is, so I'm eager to roll this out when the remainder of the todo list is check off. I'll keep an eye on this going forward!

**Comment by malsf21** [comment]
Ok with that, we've hit everything on the to-do list other than the bugfix on large screens - @emmyc can you take a look at that when you have a chance.

Stretch goals should be adding some sort of testing, refactoring some of this code into util/helper functions, and making this much more mobile-friendly (though it does work as intended on mobile, just could be spicier). @krashanoff you can probably look to review/merge whenever.

**Comment by malsf21** [comment]
@krashanoff just pushed a commit that should fix the svg not filling for the screen being too large, lmk what you think! I will say, the actual image itself looks slightly strange, but I think it's nbd.

As per super short screens & mobile, we probably do need to do something about it eventually - but also not sure as to what the plan is.

**Comment by krashanoff** [comment]
Got it! Will check it out later this evening or tomorrow morning. Thanks Matt!

Regarding mobile screens, it isn't ideal, but it honestly isn't much worse than our current mobile experience:

image

We'll handle it another day.

**Pull request merged**
