### PR TITLE
Adds Language Icon to Editor Pane's Program Dropdown

### PR DESCRIPTION
**Pull request by malsf21**
I've been procrastinating doing the sketches finishing touches, so instead I quickly added the language icon to the editor dropdown. @connorbo97 , do you think this is the most elegant way to do this? Not sure if there's a more Immutable-y way to do it. Let me know what you think!

### CODE REVIEW

**Comment by malsf21** [comment]
Also, as a side note - it breaks on Travis because of an unused variable in the `find` function in `DropdownButtonContainer.js` - this is because I need to specify (value, key) in the function, but I only need key (but need to specify value). Am I using the wrong function for this? Looked through the Immutable docs but couldn't find what I needed.

**Comment by connorbo97** [comment]
Can't look rn, but if you have an unused param, you could use _ instead of giving it a name?

**Comment by malsf21** [comment]
Mm good point, I'll give it a shot. No rush ofc, but lmk if you know a better function to use. The actual feature works as intended.

**Comment by malsf21** [comment]
Ok, I changed it so that all the programs in the dropdown menu have icons, and the way I did it then removed all the jank. I think it's not bad now, what are your thoughts?

**Pull request merged**
