### PR TITLE
Fix username

### PR DESCRIPTION
**Pull request by willob99**
Fixes the bug where the bad username message wouldn't appear. Removes the profanity filter.

### CODE REVIEW

**Comment by connorbo97** [comment]
Looks good. Once someone else takes a look and approves, you can merge :)

**Comment by malsf21** [comment]
Agh, a merge conflict. I'll see if I can fix this one.

**Comment by malsf21** [comment]
@connorbo97 @willob99 I believe I've correctly fixed the merge conflict and created a working solution. I've built it on my own computer and it's passed the CI. Can one of you two do me a favour and double-check that I've done it properly, by running the app on your computer?

**Comment by connorbo97** [comment]
Looks good to me locally @malsf21.

**Comment by malsf21** [comment]
Awesome, gonna merge!

**Pull request merged**
